In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import statsmodels.api as sm
from sklearn import linear_model as lm

In [2]:
x_1 = np.random.uniform(10,40,100)
x_2 = np.random.uniform(-50,20,100)
x_3 = np.random.uniform(20,60,100)
x_4 = np.random.uniform(10,40,100)
x_5 = np.random.uniform(-50,20,100)
x_6 = np.random.uniform(20,60,100)
epsilon = np.random.normal(0,10,100)

In [3]:
y=-30+1.3*x_1+1.6*x_2+1.1*x_3+0.7*x_4-2.1*x_5-0.9*x_6+epsilon

In [4]:
X_ols=pd.DataFrame()
X_ols['Constant']=pd.Series(np.ones(100))
X_ols['X1'] = pd.Series(x_1)
X_ols['X2'] = pd.Series(x_2)
X_ols['X3'] = pd.Series(x_3)
X_ols['X4'] = pd.Series(x_4)
X_ols['X5'] = pd.Series(x_5)
X_ols['X6'] = pd.Series(x_6)

In [5]:
model_reg = sm.OLS(y,X_ols).fit()
model_reg.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.968
Model:                            OLS   Adj. R-squared:                  0.966
Method:                 Least Squares   F-statistic:                     465.5
Date:                Mon, 02 Oct 2023   Prob (F-statistic):           4.60e-67
Time:                        16:09:23   Log-Likelihood:                -370.99
No. Observations:                 100   AIC:                             756.0
Df Residuals:                      93   BIC:                             774.2
Df Model:                           6                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Constant     -35.8260      6.778     -5.286      0.000     -49.285     -22.366
X1             1.4355      0.124     11.619      0.000       1.190       1.681
X2             1.5884      0.055     28.744      0.000       1.479       1.698
X3             1.0615      0.100     10.618      0.000       0.863       1.260
X4             0.5289      0.118      4.479      0.000       0.294       0.763
X5            -2.0991      0.053    -39.533      0.000      -2.205      -1.994
X6            -0.7404      0.092     -8.092      0.000      -0.922      -0.559
==============================================================================
Omnibus:                        1.860   Durbin-Watson:                   2.058
Prob(Omnibus):                  0.395   Jarque-Bera (JB):                1.524
Skew:                           0.138   Prob(JB):                        0.467
Kurtosis:                       2.461   Cond. No.                         465.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [7]:
# Now we add some unrelated coefficients
x_7 = np.random.uniform(10,40,100)
x_8 = np.random.uniform(-50,20,100)
x_9 = np.random.uniform(20,60,100)
x_10 = np.random.uniform(10,40,100)
x_11 = np.random.uniform(-50,20,100)
x_12 = np.random.uniform(20,60,100)

In [8]:
X_ext = pd.DataFrame()
X_ext['Constant']=pd.Series(np.ones(100))
X_ext['X1'] = pd.Series(x_1)
X_ext['X2'] = pd.Series(x_2)
X_ext['X3'] = pd.Series(x_3)
X_ext['X4'] = pd.Series(x_4)
X_ext['X5'] = pd.Series(x_5)
X_ext['X6'] = pd.Series(x_6)
X_ext['X7'] = pd.Series(x_7)
X_ext['X8'] = pd.Series(x_8)
X_ext['X9'] = pd.Series(x_9)
X_ext['X10'] = pd.Series(x_10)
X_ext['X11'] = pd.Series(x_11)
X_ext['X12'] = pd.Series(x_12)

In [9]:
model_reg = sm.OLS(y,X_ext).fit()
model_reg.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.970
Model:                            OLS   Adj. R-squared:                  0.966
Method:                 Least Squares   F-statistic:                     232.6
Date:                Mon, 02 Oct 2023   Prob (F-statistic):           1.22e-60
Time:                        16:09:48   Log-Likelihood:                -367.79
No. Observations:                 100   AIC:                             761.6
Df Residuals:                      87   BIC:                             795.5
Df Model:                          12                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Constant     -38.0452      9.251     -4.113      0.000     -56.432     -19.659
X1             1.5129      0.131     11.511      0.000       1.252       1.774
X2             1.5785      0.057     27.850      0.000       1.466       1.691
X3             1.1036      0.103     10.675      0.000       0.898       1.309
X4             0.5174      0.120      4.301      0.000       0.278       0.756
X5            -2.1148      0.054    -39.192      0.000      -2.222      -2.008
X6            -0.7129      0.095     -7.502      0.000      -0.902      -0.524
X7             0.0330      0.122      0.271      0.787      -0.209       0.275
X8             0.1158      0.053      2.204      0.030       0.011       0.220
X9             0.0778      0.107      0.727      0.469      -0.135       0.290
X10           -0.0172      0.129     -0.134      0.894      -0.273       0.238
X11           -0.0281      0.058     -0.482      0.631      -0.144       0.088
X12           -0.1220      0.107     -1.139      0.258      -0.335       0.091
==============================================================================
Omnibus:                        5.323   Durbin-Watson:                   2.101
Prob(Omnibus):                  0.070   Jarque-Bera (JB):                2.589
Skew:                           0.068   Prob(JB):                        0.274
Kurtosis:                       2.224   Cond. No.                         887.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [10]:
# When we input the matrix, we don't need to add the column of ones because \
# Lasso automatically takes it into account

X_ext = X_ext.drop(columns=['Constant'])
model_lasso = lm.Lasso(alpha=1).fit(X_ext,y)
model_lasso.coef_

array([ 1.48990791e+00,  1.57330804e+00,  1.09175550e+00,  5.08065246e-01,
       -2.11091178e+00, -7.09271268e-01,  2.05557130e-02,  1.10156450e-01,
        5.96554472e-02, -1.17982295e-03, -2.13781038e-02, -1.07191078e-01])

In [36]:
model_lasso = lm.Lasso(alpha=10).fit(X_ext,y)
model_lasso.coef_

array([ 1.10484424,  1.51390299,  1.01218205,  0.59247201, -2.09748408,
       -0.84828585,  0.        , -0.        , -0.        , -0.        ,
       -0.        ,  0.        ])

In [41]:
# We now apply Ridge Regression to our data

model_ridge = lm.Ridge(alpha=10).fit(X_ext,y)
model_ridge.coef_

array([ 1.25127262,  1.53337585,  1.10937072,  0.70229948, -2.14587799,
       -0.93878662,  0.11997347, -0.01943572, -0.0270754 , -0.05503608,
       -0.04212088,  0.06266356])

In [42]:
model_ridge = lm.Ridge(alpha=10000).fit(X_ext,y)
model_ridge.coef_

array([ 0.50321658,  1.21756962,  0.57935289,  0.32105205, -1.62079055,
       -0.42170529,  0.00375219, -0.07646285,  0.07164929,  0.05336775,
        0.01281994,  0.08499685])